/* A small, local demonstration catalogue, not a live security master or quote feed. */
(() => {
  'use strict';
  const rows = [
    ['CN','600519','贵州茅台','gzmt','guizhoumaotai','consumer',['茅台','maotai']],
    ['CN','300750','宁德时代','ndsd','ningdeshidai','ev',['宁德','CATL']],
    ['CN','600036','招商银行','zsyh','zhaoshangyinhang','finance',['招行']],
    ['CN','601318','中国平安','zgpa','zhongguopingan','finance',['平安']],
    ['CN','600900','长江电力','cjdl','changjiangdianli','energy',[]],
    ['CN','600030','中信证券','zxzq','zhongxinzhengquan','finance',[]],
    ['CN','000001','平安银行','payh','pinganyinhang','finance',[]],
    ['CN','000333','美的集团','mdjt','meidijituan','hardware',['美的','Midea']],
    ['CN','000651','格力电器','gldq','gelidianqi','hardware',['格力','Gree']],
    ['CN','000858','五粮液','wly','wuliangye','consumer',[]],
    ['CN','002594','比亚迪','byd','biyadi','ev',['BYD']],
    ['CN','002475','立讯精密','lxjm','lixunjingmi','hardware',[]],
    ['CN','000725','京东方A','jdfa','jingdongfanga','hardware',['京东方','BOE']],
    ['CN','002415','海康威视','hkws','haikangweishi','hardware',['海康','Hikvision']],
    ['CN','600584','长电科技','cdkj','changdiankeji','chips',[]],
    ['CN','688981','中芯国际','zxgj','zhongxinguoji','chips',['中芯','SMIC']],
    ['CN','688012','中微公司','zwgs','zhongweigongsi','chips',['中微','AMEC']],
    ['CN','688256','寒武纪','hwj','hanwuji','chips',['Cambricon']],
    ['CN','300308','中际旭创','zjxc','zhongjixuchuang','hardware',[]],
    ['CN','300502','新易盛','xys','xinyisheng','hardware',[]],
    ['CN','300059','东方财富','dfcf','dongfangcaifu','finance',['东财','Eastmoney']],
    ['CN','300339','润和软件','rhrj','runheruanjian','software',[]],
    ['CN','600410','华胜天成','hstc','huashengtiancheng','software',[]],
    ['CN','002261','拓维信息','twxx','tuoweixinxi','software',[]],
    ['CN','601012','隆基绿能','ljln','longjilvneng','energy',['隆基','LONGi']],
    ['CN','600438','通威股份','twgf','tongweigufen','energy',['通威']],
    ['CN','002050','三花智控','shzk','sanhuazhikong','industry',['三花']],
    ['CN','601138','工业富联','gyfl','gongyefulian','hardware',['富士康工业互联网','FII']],
    ['CN','601398','工商银行','gsyh','gongshangyinhang','finance',['工行','ICBC']],
    ['CN','601857','中国石油','zgsy','zhongguoshiyou','energy',['中石油','PetroChina']],
    ['CN','601888','中国中免','zgzm','zhongguozhongmian','consumer',['中免']],
    ['CN','603259','药明康德','ymkd','yaomingkangde','health',['WuXi AppTec']],
    ['CN','600276','恒瑞医药','hryy','hengruiyiyao','health',['恒瑞']],
    ['CN','600309','万华化学','whhx','wanhuahuaxue','industry',['万华']],
    ['CN','601127','赛力斯','sls','sailisi','ev',['Seres']],
    ['CN','002714','牧原股份','mygf','muyuangufen','consumer',['牧原']],
    ['CN','600887','伊利股份','ylgf','yiligufen','consumer',['伊利','Yili']],
    ['CN','601899','紫金矿业','zjky','zijinkuangye','energy',['紫金']],
    ['CN','600150','中国船舶','zgcb','zhongguochuanbo','industry',[]],
    ['CN','600893','航发动力','hfdl','hangfadongli','industry',[]],
    ['CN','920799','艾融软件','arrj','airongruanjian','software',['艾融']],
    ['CN','920185','贝特瑞','btr','beiterui','ev',[]],
    ['HK','00700','腾讯控股','txkg','tengxunkonggu','internet',['腾讯','Tencent']],
    ['HK','09988','阿里巴巴','albb','alibaba','internet',['阿里','阿里巴巴-W']],
    ['HK','03690','美团','mt','meituan','internet',['美团-W']],
    ['HK','01810','小米集团','xmjt','xiaomijituan','hardware',['小米','Xiaomi','小米集团-W']],
    ['HK','00981','中芯国际','zxgj','zhongxinguoji','chips',['中芯','SMIC']],
    ['HK','09866','蔚来','wl','weilai','ev',['蔚来-SW']],
    ['HK','02015','理想汽车','lxqc','lixiangqiche','ev',['理想','理想汽车-W']],
    ['HK','09868','小鹏汽车','xpqc','xiaopengqiche','ev',['小鹏','小鹏汽车-W']],
    ['HK','01211','比亚迪股份','bydgf','biyadigufen','ev',['比亚迪','BYD']],
    ['HK','00883','中国海洋石油','zghysy','zhongguohaiyangshiyou','energy',['中海油','CNOOC']],
    ['HK','00939','建设银行','jsyh','jiansheyinhang','finance',['建行','CCB']],
    ['HK','01398','工商银行','gsyh','gongshangyinhang','finance',['工行','ICBC']],
    ['HK','02318','中国平安','zgpa','zhongguopingan','finance',['平安']],
    ['HK','02382','舜宇光学科技','sygxkj','shunyuguangxuekeji','hardware',['舜宇光学','Sunny Optical']],
    ['HK','00941','中国移动','zgyd','zhongguoyidong','internet',['移动','China Mobile']],
    ['HK','01024','快手','ks','kuaishou','internet',['快手-W']],
    ['HK','09618','京东集团','jdjt','jingdongjituan','internet',['京东','京东集团-SW']],
    ['HK','09999','网易','wy','wangyi','internet',['网易-S','NetEase']],
    ['HK','00992','联想集团','lxjt','lianxiangjituan','hardware',['联想','Lenovo']],
    ['HK','02331','李宁','ln','lining','consumer',[]],
    ['HK','09961','携程集团','xcjt','xiechengjituan','internet',['携程','Trip.com']],
    ['HK','03968','招商银行','zsyh','zhaoshangyinhang','finance',['招行']],
    ['HK','03750','宁德时代','ndsd','ningdeshidai','ev',['宁德','CATL']],
    ['HK','01801','信达生物','xdsw','xindashengwu','health',['信达','Innovent']],
    ['US','NVDA','英伟达','ywd','yingweida','chips',['NVIDIA']],
    ['US','AAPL','苹果','pg','pingguo','hardware',['Apple']],
    ['US','MSFT','微软','wr','weiruan','software',['Microsoft']],
    ['US','GOOGL','谷歌 A 类','gg','guge','internet',['谷歌','Google','Alphabet']],
    ['US','GOOG','谷歌 C 类','gg','guge','internet',['谷歌','Google','Alphabet']],
    ['US','AMZN','亚马逊','ymx','yamaxun','internet',['Amazon']],
    ['US','META','Meta','meta','meta','internet',['脸书','Facebook']],
    ['US','TSLA','特斯拉','tsl','tesila','ev',['Tesla']],
    ['US','AMD','超微半导体','cwbdt','chaoweibandaoti','chips',['超威半导体','超微','Advanced Micro Devices']],
    ['US','INTC','英特尔','yte','yingteer','chips',['Intel']],
    ['US','AVGO','博通','bt','botong','chips',['Broadcom']],
    ['US','TSM','台积电','tjd','taijidian','chips',['TSMC']],
    ['US','BABA','阿里巴巴','albb','alibaba','internet',['阿里']],
    ['US','JD','京东','jd','jingdong','internet',['JD.com']],
    ['US','PDD','拼多多','pdd','pinduoduo','internet',['PDD Holdings']],
    ['US','NIO','蔚来','wl','weilai','ev',[]],
    ['US','LI','理想汽车','lxqc','lixiangqiche','ev',['理想','Li Auto']],
    ['US','XPEV','小鹏汽车','xpqc','xiaopengqiche','ev',['小鹏','XPeng']],
    ['US','TME','腾讯音乐','txyy','tengxunyinyue','internet',['Tencent Music']],
    ['US','BIDU','百度','bd','baidu','internet',[]],
    ['US','NTES','网易','wy','wangyi','internet',['NetEase']],
    ['US','NFLX','奈飞','nf','naifei','internet',['网飞','Netflix']],
    ['US','PLTR','Palantir','pltr','palantir','software',['帕兰提尔']],
    ['US','COIN','Coinbase','coin','coinbase','finance',[]],
    ['US','UBER','优步','yb','youbu','internet',['Uber']],
    ['US','CRM','Salesforce','crm','salesforce','software',['赛富时']],
    ['US','ORCL','甲骨文','jgw','jiaguwen','software',['Oracle']],
    ['US','NKE','耐克','nk','naike','consumer',['Nike']],
    ['US','KO','可口可乐','kkkl','kekoukele','consumer',['Coca-Cola']],
    ['US','JPM','摩根大通','mgdt','mogendatong','finance',['JPMorgan']],
    ['US','V','Visa','visa','visa','finance',['维萨']],
    ['US','DIS','迪士尼','dsn','dishini','internet',['Disney']]
  ];
  const stocks = rows.map(([market,code,name,initials,pinyin,sector,aliases]) => Object.freeze({
    id:`${market}:${code}`,market,code,name,initials,pinyin,sector,aliases,
    exchange:market === 'CN' ? (code.startsWith('6') ? '沪市' : code.startsWith('9') ? '北交所' : '深市') : market === 'HK' ? '港股' : '美股'
  }));
  // These are conditional educational templates. They do not assert current market conditions.
  const sectors = {
    chips:{name:'半导体',industry:'关注订单、产能利用率和盈利预期是否同步改善。只有行业需求真正转化为公司收入，景气预期才更有依据。',news:'核实新品发布、产能扩张和客户订单的公告来源，区分技术进展与已经兑现的商业收入。',tags:['订单变化','产能利用率','盈利预期']},
    consumer:{name:'消费',industry:'关注终端需求、渠道库存和利润率的变化。品牌热度需要与实际销量及现金流相互验证。',news:'对产品提价、促销和消费政策等信息，先确认正式公告，再观察是否真正影响收入和利润。',tags:['终端需求','渠道库存','现金流']},
    finance:{name:'金融服务',industry:'结合具体业务，关注盈利质量、资产风险和市场活跃度。对银行、保险、券商及交易平台，应使用各自适用的指标。',news:'区分政策预期与正式落地，对业绩、分红和监管信息，优先核对公司及监管机构的原始公告。',tags:['盈利质量','资产风险','业务指标']},
    ev:{name:'汽车与新能源',industry:'关注交付或出货量、单价与毛利率是否协调改善。销量增长不一定等于利润增长，还需观察竞争和现金流。',news:'核实新产品、订单及产业政策的适用范围，区分意向订单、实际交付和已经确认的收入。',tags:['出货与交付','毛利率','竞争格局']},
    internet:{name:'互联网与服务',industry:'关注用户需求、收入增长和投入效率。业务热度需要结合利润率及现金流，判断能否持续转化为经营成果。',news:'对新业务、合作或产品发布，核实信息出处与具体条款，避免将社交媒体热度直接当作业绩增量。',tags:['收入增长','投入效率','现金流']},
    industry:{name:'工业制造',industry:'关注在手订单、交付进度、成本和回款。订单增长需要与产能、利润率及应收账款质量一起看。',news:'核实合同规模、履约周期和业绩影响，区分框架协议、正式订单与已经交付的项目。',tags:['订单质量','交付进度','成本与回款']},
    health:{name:'医药健康',industry:'关注研发进展、商业化能力与现金流。不同研发阶段的项目存在不同的不确定性，需要结合公司实际业务判断。',news:'对临床试验、监管审批和授权合作，核实阶段、适应症及条款，不把单一进展直接等同于未来利润。',tags:['研发进展','商业化','现金储备']},
    energy:{name:'能源与资源',industry:'结合具体业务，关注供需、产品价格、成本与现金流。不同能源和资源品的周期并不相同，不能用同一个景气判断套用。',news:'核实政策、产能、资源项目和价格变动的信息来源，判断其影响是短期扰动还是持续变化。',tags:['供需变化','成本结构','现金流']},
    software:{name:'软件服务',industry:'关注客户需求、合同转化与盈利质量。技术概念需要通过真实客户、收入和回款得到验证。',news:'核实产品发布、合作关系和项目订单的实质内容，区分技术展示、试点项目与商业落地。',tags:['客户需求','收入转化','合同与回款']},
    hardware:{name:'硬件与设备',industry:'关注产品需求、出货量、库存和利润率。还要观察主要客户或产品的集中度，避免只看新品预期。',news:'对新品、供应链合作和扩产消息，先核实公司公告，再判断订单规模、交付时间和盈利影响。',tags:['产品需求','库存变化','利润率']}
  };
  window.NiulaiCatalog = Object.freeze({stocks:Object.freeze(stocks),sectors:Object.freeze(sectors)});
})();
