/* Curated Chinese names and aliases enrich the generated full market directories. */
(() => {
  'use strict';
  const rows = [
    ['CN','600519','贵州茅台','gzmt','guizhoumaotai','consumer',['茅台','maotai']],
    ['CN','300750','宁德时代','ndsd','ningdeshidai','ev',['宁德','CATL']],
    ['CN','600036','招商银行','zsyh','zhaoshangyinhang','finance',['招行']],
    ['CN','601318','中国平安','zgpa','zhongguopingan','finance',['平安']],
    ['CN','600900','长江电力','cjdl','changjiangdianli','energy',[]],
    ['CN','600030','中信证券','zxzq','zhongxinzhengquan','finance',[]],
    ['CN','000001','平安银行','payh','pinganyinhang','finance',[]],
    ['CN','000333','美的集团','mdjt','meidijituan','hardware',['美的','Midea']],
    ['CN','000651','格力电器','gldq','gelidianqi','hardware',['格力','Gree']],
    ['CN','000858','五粮液','wly','wuliangye','consumer',[]],
    ['CN','002594','比亚迪','byd','biyadi','ev',['BYD']],
    ['CN','002475','立讯精密','lxjm','lixunjingmi','hardware',[]],
    ['CN','000725','京东方A','jdfa','jingdongfanga','hardware',['京东方','BOE']],
    ['CN','002415','海康威视','hkws','haikangweishi','hardware',['海康','Hikvision']],
    ['CN','600584','长电科技','cdkj','changdiankeji','chips',[]],
    ['CN','688981','中芯国际','zxgj','zhongxinguoji','chips',['中芯','SMIC']],
    ['CN','688012','中微公司','zwgs','zhongweigongsi','chips',['中微','AMEC']],
    ['CN','688256','寒武纪','hwj','hanwuji','chips',['Cambricon']],
    ['CN','300308','中际旭创','zjxc','zhongjixuchuang','hardware',[]],
    ['CN','300502','新易盛','xys','xinyisheng','hardware',[]],
    ['CN','300059','东方财富','dfcf','dongfangcaifu','finance',['东财','Eastmoney']],
    ['CN','300339','润和软件','rhrj','runheruanjian','software',[]],
    ['CN','600410','华胜天成','hstc','huashengtiancheng','software',[]],
    ['CN','002261','拓维信息','twxx','tuoweixinxi','software',[]],
    ['CN','601012','隆基绿能','ljln','longjilvneng','energy',['隆基','LONGi']],
    ['CN','600438','通威股份','twgf','tongweigufen','energy',['通威']],
    ['CN','002050','三花智控','shzk','sanhuazhikong','industry',['三花']],
    ['CN','601138','工业富联','gyfl','gongyefulian','hardware',['富士康工业互联网','FII']],
    ['CN','601398','工商银行','gsyh','gongshangyinhang','finance',['工行','ICBC']],
    ['CN','601857','中国石油','zgsy','zhongguoshiyou','energy',['中石油','PetroChina']],
    ['CN','601888','中国中免','zgzm','zhongguozhongmian','consumer',['中免']],
    ['CN','603259','药明康德','ymkd','yaomingkangde','health',['WuXi AppTec']],
    ['CN','600276','恒瑞医药','hryy','hengruiyiyao','health',['恒瑞']],
    ['CN','600309','万华化学','whhx','wanhuahuaxue','industry',['万华']],
    ['CN','601127','赛力斯','sls','sailisi','ev',['Seres']],
    ['CN','002714','牧原股份','mygf','muyuangufen','consumer',['牧原']],
    ['CN','600887','伊利股份','ylgf','yiligufen','consumer',['伊利','Yili']],
    ['CN','601899','紫金矿业','zjky','zijinkuangye','energy',['紫金']],
    ['CN','600150','中国船舶','zgcb','zhongguochuanbo','industry',[]],
    ['CN','600893','航发动力','hfdl','hangfadongli','industry',[]],
    ['CN','920799','艾融软件','arrj','airongruanjian','software',['艾融']],
    ['CN','920185','贝特瑞','btr','beiterui','ev',[]],
    ['HK','00700','腾讯控股','txkg','tengxunkonggu','internet',['腾讯','Tencent']],
    ['HK','09988','阿里巴巴','albb','alibaba','internet',['阿里','阿里巴巴-W']],
    ['HK','03690','美团','mt','meituan','internet',['美团-W']],
    ['HK','01810','小米集团','xmjt','xiaomijituan','hardware',['小米','Xiaomi','小米集团-W']],
    ['HK','00981','中芯国际','zxgj','zhongxinguoji','chips',['中芯','SMIC']],
    ['HK','09866','蔚来','wl','weilai','ev',['蔚来-SW']],
    ['HK','02015','理想汽车','lxqc','lixiangqiche','ev',['理想','理想汽车-W']],
    ['HK','09868','小鹏汽车','xpqc','xiaopengqiche','ev',['小鹏','小鹏汽车-W']],
    ['HK','01211','比亚迪股份','bydgf','biyadigufen','ev',['比亚迪','BYD']],
    ['HK','00883','中国海洋石油','zghysy','zhongguohaiyangshiyou','energy',['中海油','CNOOC']],
    ['HK','00939','建设银行','jsyh','jiansheyinhang','finance',['建行','CCB']],
    ['HK','01398','工商银行','gsyh','gongshangyinhang','finance',['工行','ICBC']],
    ['HK','02318','中国平安','zgpa','zhongguopingan','finance',['平安']],
    ['HK','02382','舜宇光学科技','sygxkj','shunyuguangxuekeji','hardware',['舜宇光学','Sunny Optical']],
    ['HK','00941','中国移动','zgyd','zhongguoyidong','internet',['移动','China Mobile']],
    ['HK','01024','快手','ks','kuaishou','internet',['快手-W']],
    ['HK','09618','京东集团','jdjt','jingdongjituan','internet',['京东','京东集团-SW']],
    ['HK','09999','网易','wy','wangyi','internet',['网易-S','NetEase']],
    ['HK','00992','联想集团','lxjt','lianxiangjituan','hardware',['联想','Lenovo']],
    ['HK','02331','李宁','ln','lining','consumer',[]],
    ['HK','09961','携程集团','xcjt','xiechengjituan','internet',['携程','Trip.com']],
    ['HK','03968','招商银行','zsyh','zhaoshangyinhang','finance',['招行']],
    ['HK','03750','宁德时代','ndsd','ningdeshidai','ev',['宁德','CATL']],
    ['HK','01801','信达生物','xdsw','xindashengwu','health',['信达','Innovent']],
    ['US','NVDA','英伟达','ywd','yingweida','chips',['NVIDIA']],
    ['US','AAPL','苹果','pg','pingguo','hardware',['Apple']],
    ['US','MSFT','微软','wr','weiruan','software',['Microsoft']],
    ['US','GOOGL','谷歌 A 类','gg','guge','internet',['谷歌','Google','Alphabet']],
    ['US','GOOG','谷歌 C 类','gg','guge','internet',['谷歌','Google','Alphabet']],
    ['US','AMZN','亚马逊','ymx','yamaxun','internet',['Amazon']],
    ['US','META','Meta','meta','meta','internet',['脸书','Facebook']],
    ['US','TSLA','特斯拉','tsl','tesila','ev',['Tesla']],
    ['US','AMD','超微半导体','cwbdt','chaoweibandaoti','chips',['超威半导体','超微','Advanced Micro Devices']],
    ['US','INTC','英特尔','yte','yingteer','chips',['Intel']],
    ['US','AVGO','博通','bt','botong','chips',['Broadcom']],
    ['US','TSM','台积电','tjd','taijidian','chips',['TSMC']],
    ['US','BABA','阿里巴巴','albb','alibaba','internet',['阿里']],
    ['US','JD','京东','jd','jingdong','internet',['JD.com']],
    ['US','PDD','拼多多','pdd','pinduoduo','internet',['PDD Holdings']],
    ['US','NIO','蔚来','wl','weilai','ev',[]],
    ['US','LI','理想汽车','lxqc','lixiangqiche','ev',['理想','Li Auto']],
    ['US','XPEV','小鹏汽车','xpqc','xiaopengqiche','ev',['小鹏','XPeng']],
    ['US','TME','腾讯音乐','txyy','tengxunyinyue','internet',['Tencent Music']],
    ['US','BIDU','百度','bd','baidu','internet',[]],
    ['US','NTES','网易','wy','wangyi','internet',['NetEase']],
    ['US','NFLX','奈飞','nf','naifei','internet',['网飞','Netflix']],
    ['US','PLTR','Palantir','pltr','palantir','software',['帕兰提尔']],
    ['US','COIN','Coinbase','coin','coinbase','finance',[]],
    ['US','UBER','优步','yb','youbu','internet',['Uber']],
    ['US','CRM','Salesforce','crm','salesforce','software',['赛富时']],
    ['US','ORCL','甲骨文','jgw','jiaguwen','software',['Oracle']],
    ['US','NKE','耐克','nk','naike','consumer',['Nike']],
    ['US','KO','可口可乐','kkkl','kekoukele','consumer',['Coca-Cola']],
    ['US','JPM','摩根大通','mgdt','mogendatong','finance',['JPMorgan']],
    ['US','V','Visa','visa','visa','finance',['维萨']],
    ['US','DIS','迪士尼','dsn','dishini','internet',['Disney']]
  ];
  const stocks = rows.map(([market,code,name,initials,pinyin,sector,aliases]) => Object.freeze({
    id:`${market}:${code}`,market,code,name,initials,pinyin,sector,aliases,
    exchange:market === 'CN' ? (code.startsWith('6') ? '沪市' : code.startsWith('9') ? '北交所' : '深市') : market === 'HK' ? '港股' : '美股'
  }));
  window.NiulaiCatalog = Object.freeze({stocks:Object.freeze(stocks)});
})();
